[tools]
"cargo:bacon" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:mprocs" = "latest"
"cargo:zoxide" = "latest"
go = "latest"
lua = "latest"
node = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"
